# Generated by Django 4.1.5 on 2023-02-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("best_version", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="best_version",
            field=models.CharField(default="23.2.1", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="user_name",
            field=models.CharField(default="rajiv", max_length=200),
            preserve_default=False,
        ),
    ]
