# Generated by Django 4.1.5 on 2023-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_version', '0003_goal_best_version_goal_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestMoment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('best_version', models.CharField(max_length=200)),
                ('best_moment_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProudMoment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('best_version', models.CharField(max_length=200)),
                ('proud_moment_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('best_version', models.CharField(max_length=200)),
            ],
        ),
    ]
